# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloak < Formula
  desc "protect environmental vars from untrusted applications"
  homepage ""
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/DavidHoenisch/cloak/releases/download/v0.1.3/cloak_0.1.3_darwin_amd64.tar.gz"
      sha256 "df8d9af8a6ce334602cfab7a2d9a4d4a46d5189046bb030eca79a659b42e7f81"

      def install
        bin.install "cloak"
      end
    end
    on_arm do
      url "https://github.com/DavidHoenisch/cloak/releases/download/v0.1.3/cloak_0.1.3_darwin_arm64.tar.gz"
      sha256 "dd7d029c825b78956f65e69c2fb171cf38df8f38c2324c108f1e7aadbaf11df4"

      def install
        bin.install "cloak"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DavidHoenisch/cloak/releases/download/v0.1.3/cloak_0.1.3_linux_amd64.tar.gz"
        sha256 "9f6f71f92ad4f12ec4a085795c7677370fb37b5ad60247fccc86262584e60919"

        def install
          bin.install "cloak"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DavidHoenisch/cloak/releases/download/v0.1.3/cloak_0.1.3_linux_arm64.tar.gz"
        sha256 "123e9373a7f1a8c5ef418890003740e1024998afe6a25fe7091475898788e1f5"

        def install
          bin.install "cloak"
        end
      end
    end
  end

  test do
    system "#{bin}/cloak --version"
  end
end
